# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ca4281aae99eaf173636bf4bef07a3e4cefc136543c81854b5728e23f50cf223698195b38217b7a96d2e297b546abb0422544f34533e8d639b79e6744bb84e3

test:
  secret_key_base: 5a52a7b34d4a92b0dfaf975287d5b165b35cd74b065e476ac6e2a876f8723124bc3e625381006fd5ec87aa101edc43f9474fcd883dfc044b7bc4542c8b9da32f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
